name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Enable Flutter Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          echo "PEXEL_API_KEY=${{ secrets.PEXEL_API_KEY }}" >> .env
        
      - name: Build Web
        run: flutter build web --release --base-href /Wallpaper-App/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'